### ISSUE TITLE
Edge case for jasmine init using node

### ISSUE THREAD

**Issue by mcnichol** [jasmine/jasmine#1066]
This may be a very unlikely and trivial edge case, but wanted to bring it up.  

When running ```jasmine init``` within a folder that already has a **spec** folder it will look for **jasmine.json** within **spec/spec/support/jasmine.json** folder.

Granted you likely wouldn't have a spec folder if you were running jasmine init and this may be a bit too trivial.  Felt like sharing.

```javascript
Laptop:spec user$ jasmine
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/user/workspace/localrepo/spec/spec/support/jasmine.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Jasmine.loadConfigFile (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:83:16)
    at runJasmine (/usr/local/lib/node_modules/jasmine/lib/command.js:92:11)
    at Command.run (/usr/local/lib/node_modules/jasmine/lib/command.js:49:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by mcnichol** [comment]
My mistake....was actually in the spec folder.  Hindsight is 20/20.
