### ISSUE TITLE
Jasmine throws an exception when test case finishes and a call to done() is made.

### ISSUE THREAD

**Issue by mjilugu** [jasmine/jasmine#1113]
At the end of my test, jasmine throws an exception and does not proceed to the next test case. Everything in the test function executes okay until when jasmine calls the done function. 

```
at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:750:17)
    at Jasmine.module.exports [as exit] (/usr/local/lib/node_modules/jasmine/lib/exit.js:6:5)
    at /usr/local/lib/node_modules/jasmine/lib/jasmine.js:160:23
    at jasmineDone (/usr/local/lib/node_modules/jasmine/lib/reporters/exit_code_reporter.js:10:5)
    at dispatch (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1966:28)
    at ReportDispatcher.jasmineDone (/usr/local/lib/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1949:11)
```

**Comment by slackersoft** [comment]
What version of Jasmine are you using? `jasmine -v` should tell you both core and npm versions.

What operating system are you on?

I almost looks like you have something that is trying to listen to the exit event for the node process. The stacktrace shows that Jasmine is all done and is just trying to exit the process with the correct status code based on the state of your test suite, so there shouldn't be any further test cases for it to run.

**Comment by CanadianEngineer** [comment]
Hey, I'm having a similar issue. `done()` is throwing an exception for me too, but its just a console error:

`"Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out
    at ZoneAwareError (http://localhost:9876/base/src/polyfills.ts?8d67a63699a64c8ce0721c5da8532bf8af5893fc:3640:33)
    at Env.expect (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:970:15)
    at expect (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:3616:18)
    at SafeSubscriber._next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:30805:13)
    at SafeSubscriber.__tryOrUnsub (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:615:16)
    at SafeSubscriber.next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:564:22)
    at Subscriber._next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:504:26)
    at Subscriber.next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:468:18)
    at CatchSubscriber.Subscriber._next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:504:26)
    at CatchSubscriber.Subscriber.next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:468:18)
    at MapSubscriber._next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:12696:26)
    at MapSubscriber.Subscriber.next (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:468:18)
    at XMLHttpRequest.onLoad (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:56494:38)
    at ZoneDelegate.920.ZoneDelegate.invokeTask (http://localhost:9876/base/src/polyfills.ts?8d67a63699a64c8ce0721c5da8532bf8af5893fc:3015:31)
    at ProxyZoneSpec.onInvokeTask (http://localhost:9876/base/src/test.ts?dad5650f71248117cafded2f7873f7a403f3e5ce:94643:39)
    at ZoneDelegate.920.ZoneDelegate.invokeTask (http://localhost:9876/base/src/polyfills.ts?8d67a63699a64c8ce0721c5da8532bf8af5893fc:3014:36)"`

I'm on Debian 8,
`npm view jasmine version` : 2.5.3

**Comment by slackersoft** [comment]
@CanadianEngineer I think your issue is different from the one mentioned in the first post here. Based on the error message it looks like you have a call to `expect` that occurs after the `done` function has been called (or otherwise outside of any Jasmine spec).

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while, so I'm going to close it. If you have more information, or an example suite, please open a new issue. Thanks for using Jasmine!
