### ISSUE TITLE
expect().toThrow() doesn't work

### ISSUE THREAD

**Issue by borisovg** [jasmine/jasmine#1161]
code.js
````
/*jshint node:true*/
'use strict';

exports.throw_error = function () {
    throw new Error('ALL YOUR BASE');
};
````

spec/TestSpec.js
````
/*jshint node:true, jasmine:true*/
'use strict';

var code = require('../code.js');

describe('code.js', function () {
    it('test throw_error method', function () {
        expect(code.throw_error()).toThrow();
    });
});
````

Result
````
$ jasmine spec/TestSpec.js 
Started
F

Failures:
1) code.js test throw_error method
  Message:
    Error: ALL YOUR BASE
  Stack:
    Error: ALL YOUR BASE
        at Object.exports.throw_error (/home/borisov/test/jasmine/code.js:5:11)
        at Object.<anonymous> (/home/borisov/test/jasmine/spec/TestSpec.js:8:21)

1 spec, 1 failure
Finished in 0.008 seconds
````

Version
````
$ jasmine -v
jasmine v2.4.1
jasmine-core v2.4.1
````

**Comment by Gerg** [comment]
Your problem is that you are calling your function in your test, so it blows up before it has a chance to match. `toThrow` takes a function and calls it itself.

You can either do:
```js
expect(code.throw_error).toThrow();
```

or if you need arguments: 

```js
expect(function () {
 code.throw_error(1,2,3) 
}).toThrow();
```

**Comment by borisovg** [comment]
Oops, my bad - should have read the docs more carefully - thanks!
