### ISSUE TITLE
Error during "jasmine -v"

### ISSUE THREAD

**Issue by walterdolce** [jasmine/jasmine#1166]
By running `jasmine -v`, I get:

```
jasmine v2.4.1
module.js:442
    throw err;
    ^

Error: Cannot find module '../node_modules/jasmine-core/package.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.version [as action] ({{MY_PATH}}/node_modules/jasmine/lib/command.js:174:28)
    at Command.run ({{MY_PATH}}/node_modules/jasmine/lib/command.js:47:20)
    at Object.<anonymous> ({{MY_PATH}}/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

Node version: `v6.3.1`
Npm: `3.10.3`
OS is Mac OS X El Capitan

**Comment by slackersoft** [comment]
I believe this should be fixed as of jasmine/jasmine-npm@2b511fb596e3b97e4a604aeaec4bca796e07bace which should be included in the 2.5.x releases. 

We're working on solving some other issues with the 2.5.x release of jasmine-npm right now, so it may be best to wait before updating until we've fixed jasmine/jasmine-npm#88.

Closing this. Please let us know if this doesn't appear to be fixed.
