### ISSUE TITLE
stopSpecOnExpectationFailure does not work in asynchronous specs

### ISSUE THREAD

**Issue by juliemr** [jasmine/jasmine#1213]
Using Jasmine 2.5.2, running in node.

`stopSpecOnExpectationFailure` will throw an uncaught exception and cause the process to just exit if it's used with an asynchronous spec. This means that reporters don't get a chance to print final output, and wrappers get no chance to recover and shut down gracefully.

For example, with this config:

```json
{
  "stopSpecOnExpectationFailure": true,
  "spec_dir": "",
  "spec_files": [
    "spec.js"
  ]
}
```

and this spec file:

```js
describe('async foo', function() {
  it('should bar', function(done) {
    setTimeout(function() {
      expect(1).toEqual(2);
    }, 10);
  });

  it('should baz', function() {
    expect(1).toEqual(1);
  });
});
```

Instead of getting some nice output, I get:

```
$ node node_modules/jasmine/bin/jasmine.js JASMINE_CONFIG_PATH=config.json
Started

/Users/ralphj/jasminetest/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:349
        throw new j$.errors.ExpectationFailed();
        ^
Error
    at Object.getJasmineRequireObj.errors (/Users/ralphj/jasminetest/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2761:33)
    at Object.getJasmineRequire.core (/Users/ralphj/jasminetest/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:49:26)
    at Object.module.exports [as boot] (/Users/ralphj/jasminetest/node_modules/jasmine-core/lib/jasmine-core/node_boot.js:24:32)
    at new Jasmine (/Users/ralphj/jasminetest/node_modules/jasmine/lib/jasmine.js:15:30)
    at Object.<anonymous> (/Users/ralphj/jasminetest/node_modules/jasmine/bin/jasmine.js:7:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by Gerg** [comment]
This seems like it might only be a node issue. I just tested it in a browser, and it seemed to work as expected.

**Comment by slackersoft** [comment]
I think this is really a specific case of #529. Jasmine does need some way to associate `Error`s that occur in asynchronous code to the spec that is currently executing, but I we want to keep it generic.

I'm going to close this issue in favor of #529, since solving that issue should also solve this one. Thanks for using Jasmine!
