### ISSUE TITLE
UI is not recreated properly in 2.5+ when window.onload is called multiple times

### ISSUE THREAD

**Issue by dmitrijs** [jasmine/jasmine#1220]
I was following this guide to setup Angular2 testing in Jasmine: https://www.xplatform.rocks/2016/02/01/testing-angular2-apps-with-jasmine-and-typescript/

Version 2.4+ works fine, however when updating to version 2.5+, UI is not displayed correctly. See screenshots:

Jasmine 2.4.1
![image](https://cloud.githubusercontent.com/assets/1521401/19214084/6f619360-8d84-11e6-9922-13cba845904e.png)

Jasmine 2.5.2
![image](https://cloud.githubusercontent.com/assets/1521401/19214088/9bf39608-8d84-11e6-99b3-d6d41c815ecd.png)

Error in console:
```
zone.js@0.6.25?main=browser:357 TypeError: Cannot read property 'spies' of undefined
    at currentSpies (https://unpkg.com/jasmine-core@2.5.2/lib/jasmine-core/jasmine.js:803:53)
    at SpyRegistry.clearSpies (https://unpkg.com/jasmine-core@2.5.2/lib/jasmine-core/jasmine.js:2123:19)
    at clearResourcesForRunnable (https://unpkg.com/jasmine-core@2.5.2/lib/jasmine-core/jasmine.js:615:21)
    at https://unpkg.com/jasmine-core@2.5.2/lib/jasmine-core/jasmine.js:777:9
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.25?main=browser:236:37)
    at Zone.runTask (https://unpkg.com/zone.js@0.6.25?main=browser:136:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.6.25?main=browser:368:35)
    at XMLHttpRequest.ZoneTask.invoke (https://unpkg.com/zone.js@0.6.25?main=browser:308:25)
```

 - What version are you using?
2.5.2 (reproducible since 2.5.0)

 - What environment are you running Jasmine in (node, browser, etc)?
browser

 - How are you running Jasmine (standalone, npm, karma, etc)?
standalone

 - If possible, include an example spec that demonstrates your issue.
any spec

**Comment by slackersoft** [comment]
Jasmine does not expect to have a single loaded environment executed more than once. This isn't functionality we expect to work, so I'm going to close this.

Thanks for using Jasmine!

**Comment by dmitrijs** [comment]
Ok, thanks.

Possible workaround:
```js
        (() => {
            var onloadWithJasmine = window.onload;
            window.onload = () => {};
            SystemJS.import('app/components/app/app.spec')
                    .then(onloadWithJasmine)
                    .catch(console.error.bind(console));
        })();
```
