### ISSUE TITLE
`RangeError` when using `toEqual(jasmine.any(Class)`

### ISSUE THREAD

**Issue by emilio-martinez** [jasmine/jasmine#1360]
Continuing thread from #1323.

Running Jasmine via Karma.
Jasmine: 2.6.2
Node: 6.9.5
Karma: 1.7.0
Karma Jasmine: 1.1.0
Launchers I've been using are Chrome and Phantom; both show the same issue.

I found this kind of issue as well doing this type of test for Angular 4 components:
```ts
expect(componentInstance).toEqual(jasmine.any(ComponentClass));
```
That would give me `RangeError: Invalid string length`. I've checked and both expressions evaluate to valid objects, as far as I can tell, i.e., they're not undefined, null, or something I wouldn't expect. Removing the `jasmine.any` inside the `toEqual` seems to be what did it for me; I was able to "work around" this issue like so:
```ts
expect(componentInstance instanceof ComponentClass).toBeTruthy()
```
That said, it makes me think that somehow Jasmine is running out of memory? The expressions are individually calculated correctly; it's just equality + `.any` that messes it up. Not sure how helpful it might be, but below is the stack trace that I'm getting:
```
Uncaught RangeError: Invalid string length
    at Object.<anonymous> (http://localhost:9999/base/src/test.ts:34288:45)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1154)
    at ProxyZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28429:2160)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1050)
    at Zone.run (http://localhost:9999/base/src/test.ts:28477:2925)
    at Object.<anonymous> (http://localhost:9999/base/src/test.ts:28363:131)
    at http://localhost:9999/base/src/test.ts:6511:46
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1154)
    at AsyncTestZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28268:156)
    at ProxyZoneSpec.onInvoke (http://localhost:9999/base/src/test.ts:28429:2040)
    at ZoneDelegate.invoke (http://localhost:9999/base/src/test.ts:28493:1050)
    at Zone.run (http://localhost:9999/base/src/test.ts:28477:2925)
    at AsyncTestZoneSpec._finishCallback (http://localhost:9999/base/src/test.ts:6510:13)
    at http://localhost:9999/base/src/test.ts:28265:139
    at ZoneDelegate.invokeTask (http://localhost:9999/base/src/test.ts:28493:2120)
    at Zone.runTask (http://localhost:9999/base/src/test.ts:28482:417)
    at ZoneTask.invoke (http://localhost:9999/base/src/test.ts:28495:975)
    at timer (http://localhost:9999/base/src/test.ts:28627:248)
Also worth noting is that I get a [Violation] 'setTimeout' handler took 14605ms warning in "Verbose" log mode in the Chrome Dev Tools. I believe that's because whatever's causing the error takes a bit before ending up in the RangeError.
```
The at `Object.<anonymous> [...]/test.ts:34288:45` reference at the very top refers to exactly the point where `.toEqual` is called. In my tests, I have only two instances of `.toEqual(jasmine.any(ComponentClass))`, both of which fail in the same manner. Changing to the `instanceof` approach not only removes the error but also doesn't cause a delay, therefore avoiding the Violation warning.

**Comment by emilio-martinez** [comment]
@slackersoft what ended up being the issue? Having to limit the output of the pretty printer to avoid crashing?

**Comment by slackersoft** [comment]
Best I can tell is basically an out of memory issue printing a really big object.
