### ISSUE TITLE
calling pending() on async fn will fail the test

### ISSUE THREAD

**Issue by rasjani** [jasmine/jasmine#1449]
## Suite that reproduces the behavior (for bugs)
```javascript
describe('GIVEN I have pending scenarions ', () =>  {
  it('and initial test callback is marked as async', async () => {
    pending('it causes a failure');
  });
  it('and second one is just with a normal done callback', done => {
    pending('it gets marked as pending and does not cause a failure');
    done();
  });
});
```
## Output:
```
Started
F*

Failures:
1) GIVEN I have pending scenarions  and initial test callback is marked as async
  Message:
    Failed: => marked Pendingit causes a failure
  Stack:
    Error: Failed: => marked Pendingit causes a failure
        at <anonymous>
        at runMicrotasksCallback (internal/process/next_tick.js:121:5)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
Pending:

1) GIVEN I have pending scenarions  and second one is just with a normal done callback
  it gets marked as pending and does not cause a failure

2 specs, 1 failure, 1 pending spec
Finished in 0.005 seconds
```

## Expected outcome:

Both tests should be marked as pending and who spec should not have failures.

## Current behaviour:

First testcase fails.

## Your Environment

node version: 8.7.0
jasmine: 2.8.0
windows 10 cmd & cygwin console.

**Comment by slackersoft** [comment]
Similar to #1450
