### ISSUE TITLE
Failing with unexpected reason: "Error: " and "Failed: "

### ISSUE THREAD

**Issue by amitguptagwl** [jasmine/jasmine#1649]
## Expected Behavior
Tests must pass with the latest version of jasmine.

## Current Behavior
When I run tests using jamine v3.3.1, they fail with a weird message while they are passing with jasmine v2.9.0.

```bash
  Message:
    Error: I don't like fat bodies
  Stack:
    Error: I don't like fat bodies
        at EventEmitter.muneem.setFatBodyHandler (/home/amit/git/muneem/tests/fatBody_test.js:32:11)
        at EventEmitter.emit (events.js:182:13)
        at Object.router.on [as handler] (/home/amit/git/muneem/src/routesManager.js:104:31)
        at Anumargak.lookup (/home/amit/git/muneem/node_modules/anumargak/src/letsRoute.js:404:20)
        at Server.httpHandler (/home/amit/git/muneem/src/server.js:87:32)
        at Server.emit (events.js:182:13)
        at parserOnIncoming (_http_server.js:652:12)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
  Message:
    Failed: I don't like fat bodies
  Stack:
    Error: I don't like fat bodies
        at EventEmitter.muneem.setFatBodyHandler (/home/amit/git/muneem/tests/fatBody_test.js:32:11)
        at EventEmitter.emit (events.js:182:13)
        at Object.router.on [as handler] (/home/amit/git/muneem/src/routesManager.js:104:31)
        at Anumargak.lookup (/home/amit/git/muneem/node_modules/anumargak/src/letsRoute.js:404:20)
        at Server.httpHandler (/home/amit/git/muneem/src/server.js:87:32)
        at Server.emit (events.js:182:13)
        at parserOnIncoming (_http_server.js:652:12)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

### What I'm testing
I'm running the server and throwing an error. I'm handling that error on server and responding with 500 status in this case.

```js
it('should 500 on big body.', (done) => {
        chai.request("http://localhost:3006")
            .post('/small')
            .send("This is really big body than expected")
            .then(res => {
                expect(res.status).toBe(500);
                expect(res.text).toBe("");
                done();
            }).catch( err => {
                done.fail("not expected " + err);
            });
    });
```

I can check that done is being called properly and the test must be passing. But instead, it fails with the error that I'm throwing in my code. 

## Suite that reproduces the behavior (for bugs)

```javascript
describe("sample", function() {
});
```
## Context
I'm updating dependencies and re-running tests to verify if everything is working fine.

## Your Environment

* Version used: 3.3.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 10.10.0
* Operating System and version (desktop or mobile): Ubuntu 17.10
* Link to your project: https://github.com/node-muneem/muneem/

**Comment by slackersoft** [comment]
A number of things changed in 3.0 of Jasmine, including better handling of unhandled errors and unhandled Promise rejections. We're still working on getting some of the messages for these to better indicate the situtation, but it is possible something like this is what is tripping you up. You should also try out the 2.99 release and look for any deprecation messages if you haven't already before upgrading to Jasmine 3.x

Hope this helps. Thanks for using Jasmine!

**Comment by amitguptagwl** [comment]
It worked with 2.99 so closing the issue
