### ISSUE TITLE
I get error when I run test using protractor

### ISSUE THREAD

**Issue by hassankaz** [jasmine/jasmine#1799]
I started getting this error when i run tests using jasmine.
#1491  says it should be fixed in Jasmine 3.0.and I have Jasmine 3.5..
Does anyone know what's going on and how to fix it? I really appreciate it. thank you!
-------------------

/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5120
    return children && children[0].result.status;
                                  ^

TypeError: Cannot read property 'result' of undefined
    at isAfterAll (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5120:35)
    at Suite.onException (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5083:8)
    at Suite.onException (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5095:27)
    at QueueRunner.onException (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5191:28)
    at onException (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4310:14)
    at handleError (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4243:11)
    at process.onerror (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2371:17)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.emit (/data/jenkins/workspace/run_protest_smokes_bamboo/node_modules/source-map-support/source-map-support.js:439:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! protest@1.0.0 test: `node initThirdParties.js && npx protractor conf.js "--suite" "smoke"`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the protest@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by slackersoft** [comment]
Make sure that the version of Protractor that you're using is also using a more recent Jasmine. It looks like Protractor 5.x still depends on Jasmine 2.8, but that 6.0 will use Jasmine 3.

**Comment by hassankaz** [comment]
Thank you for the tips!!  It turned out that i had still protractor 5.3.2., so I upgraded it to 6.0, but now it requires chrome 81 to run the tests. Does this make sense?

**Comment by dohrer99x** [comment]
I am having the same issue as well. I have updated:
Protractor: 6.14.2
Jasmine: 3.5.0
Chrome: 83.0

I got here from the referenced ticket stating there was a fix in 6.0

**Comment by slackersoft** [comment]
@dohrer99x it looks like somehow you're still getting the wrong version of Jasmine. If I look at line 5120 of jasmine.js in version 3.5, that line isn't in the `isAfterAll` function or even in the `Suite` object at all.

https://github.com/jasmine/jasmine/blob/v3.5.0/lib/jasmine-core/jasmine.js#L5120

It sounds like you might have a node module loading issue of some sort.

Hope this helps.

**Comment by sgravrock** [comment]
Closing since we haven't heard anything new in quite some time. If anyone's still getting this error, feel free to open a new issue after double-checking that you're using the latest versions of Jasmine, Protractor, and any other relevant dependencies.
