### ISSUE TITLE
Jasmine Spec execution fails with error ensureIsNotNested

### ISSUE THREAD

**Issue by sridattasp** [jasmine/jasmine#1853]
```
My code as below

describe("Smoke-Test-", function() {
 
    beforeAll(async function() {
		getSteps = await specGenerator.execute(); 		
	});
  
	beforeAll(async function () {
		const remote = launch.command;
		return page = PO.init(remote)
			.setFindTimeout(findTimeout)
			.setExecuteAsyncTimeout(100) 
			.maximizeWindow()
			.get(url)
			.sleep(2000);
	});
	
	let promise = new Promise((resolve,reject)=>{
    it('test', async function () {
            console.log(getSteps+"IN SPEC")
            resolve(getSteps) //execution comes here
        });
    })
	promise.then((data)=>{
    console.log(data.length+"LENGTH")
	    count = 2
		rowNumber = 2
		for(var i=0;i< count.length;i++)
		{
			..
			testRunner(ite, rowNumber) //then here
		}
	}).catch((err)=>{
    console.log(err) 
	})
	
	function testRunner(count, rowNumber) { //fail to execute here
	  it('test', async function () {	
			console.log("test"+count, rowNumber)			
			..
	    });
	} 
});
```

I have enclosed testRunner function inside a promise because it fails to trigger testRunner function, if its placed outside promise (or call like regular function)

## Expected Behavior
1. To run testRunner function which is dependent on a promise which gets value from beforeAll.

## Current Behavior
1. testRunner spec fails to execute with error as below

```
[32m. [0mError: 'it' should only be used in 'describe' function
    at ensureIsNotNested (\nodejs\node_modules\jasmine_3.5.0\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1786:15)
    at Env.it (\nodejs\node_modules\jasmine_3.5.0\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1933:7)
    at it (\nodejs\node_modules\jasmine_3.5.0\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:6576:21)
    at testRunner (\webapps\mysamples\testRunner.js:66:4)
    at \webapps\mysamples\testRunner.js:59:4
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## 
1. What is causing the failure?
2. Is there any other way to call testRunner function?

**Comment by slackersoft** [comment]
Jasmine executes your full test suite in two passes.

1. Load all the files and execute the body functions for `describe`, `xdescribe`, and `fdescribe`. Notably, the remainder of the top level Jasmine functions are _NOT_ evaluated at this time. This means that the functions passed to `it`, `beforeAll`, `beforeEach`, etc. are not evaluated until later.
2. Execute the specs one by one (in sections for suites that include `beforeAll` or `afterAll`). From this point of view a spec execution includes all `beforeEach` and `afterEach` functions associated with it.

What does this mean for you? It means that your `Promise` that encloses a call to `it` doesn't resolve until the suite starts executing (problem number one), but also that resolving that promise causes the suite to try to register another test inside the currently running test. Jasmine can't tell the difference between what you've written and something like:

```javascript
it('is a test', function() {
    it('is another test', function() {});
});
```

If you need to use a value in the `it` call that is set up asynchrously in a `beforeEach` or `beforeAll`, you'll need to save the result value (not the Promise) off as part of the setup. You can either do this with a closed over variable, or by assigning the result to a property of `this`. Take a look at the [async docs](https://jasmine.github.io/tutorials/async) for more info.

Hope this helps. Thanks for using Jasmine!

**Comment by sgravrock** [comment]
I'm closing this due to inactivity. Feel free to open a new issue with more information if you're still having trouble.
