### ISSUE TITLE
 filename is incorrect when run with angular test.

### ISSUE THREAD

**Issue by uk-taniyama** [jasmine/jasmine#2016]
### Your question

It seems that the call stack depth is different when I run it with ng test. How can I avoid it?

### Example code that demonstrates the problem

```JavaScript
When the stack is displayed with callerCallerFunction, it looks like the following.


  function callerCallerFilename() {
    console.error(new Error())
    return new j$.StackTrace(new Error()).frames[3].file;
  }
```

NOT angular:
```
Error:
    at callerCallerFilename (jasmine.js:2062:17)
    at Env.it (jasmine.js:1877:24)
    at it (jasmine.js:8133:21)
    at test.spec.js:18:3 <- hear[3]
```

Angular(Karma):
```
Error: 
    at callerCallerFilename (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?3b2bf11e62093012a891acc88ac4bc01a3d73284:2009:19)
    at Env.apply [as __zone_symbol__it] (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?3b2bf11e62093012a891acc88ac4bc01a3d73284:1855:24)
    at Env.jasmineEnv.<computed> [as it] (http://localhost:9876/_karma_webpack_/webpack:/angular-app/node_modules/zone.js/fesm2015/zone-testing.js:447:38)
    at it (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?3b2bf11e62093012a891acc88ac4bc01a3d73284:7899:21)
    at apply (http://localhost:9876/_karma_webpack_/webpack:/angular-app/src/app/app.component.spec.ts:39:3) <- hear[4]
```
```


### jasmine-core version

jasmine:5.1.0

### Versions of other relevant packages

@angular/cli:16.2.0

### Node.js or browser version

v18.16.0

### Operating System

Chrome/116.0.0.0

**Comment by sgravrock** [comment]
Please report this to the Angular project. The issue is that Zone.js monkey patches Jasmine's internals in a way that breaks caller filename detection.
