### ISSUE TITLE
.toThrow isn't async

### ISSUE THREAD

**Issue by CodeOtter** [jasmine/jasmine#916]
```

it('should not create a complete account', function(next) {
      expect(function() { 
        setTimeout(function() {
          throw new Error(); 
        });
      }, 1).toThrowError(Error);
});
```

Result
````
> api@1.0.0 test /var/www/api
> node test/run.js

Started
function () { 
        setTimeout(function() {
          throw new Error(); 
        });
      }
/var/www/api/test/controllers/TestSpec.js:36
          throw new Error(); 
                ^
Error
  at [object Object]._onTimeout (/var/www/api/test/controllers/TestSpec.js:36:17)
  at Timer.listOnTimeout (timers.js:110:15)
```

If you add this to line 3102 in jasmine-core/jasmine.js:

```
console.log('threw? ', threw);
```

You get this

```
threw? false
```

**Comment by slackersoft** [comment]
This is due to how `setTimeout` works. The function passed to `setTimeout` is executed in a new call stack, so the `catch` within the `toThrow` matcher, is unable to `catch` the exception thrown.

This isn't something we're likely to change, though we are looking at what it would take to link errors that occur in asynchronous code to the proper spec.

Thanks for using jasmine!

Closing.
